package controller;

import view.gui.CustomEventsListener;
import view.gui.CustomEvent;

/**
 * This interface represents the controller for the program.
 * It is responsible for taking in user input and running the appropriate command.
 * ------------------------------------
 * SOLID: To make the controller oblivious of the implementation of view, we will configure it
 *        to accept CustomEvents as input.
 *        This way, the controller doesn't care how the event is generated.
 *        It just cares that it is generated and passed to it.
 * ------------------------------------
 * SOLID: These CustomEvents will be generated by the view and passed to the controller.
 *        "The view is responsible for translating all user input into CustomEvents and passing
 *        them to the controller."
 * ------------------------------------
 * NOTE : This makes the controller completely independent of the view. We can use this controller
 *       with any view that generates CustomEvents. (Mobile, Desktop, voice, etc.)
 */
public interface ControllerGUIInterface extends CustomEventsListener {

  /**
   * This method runs the program.
   * It takes in a CustomEvent and runs the appropriate command.
   *
   * @param event the event to be handled.
   */
  void handleEvent(CustomEvent event);

}
